title: Navylink
description: A fast, organized launchpad for U.S. Navy and DoD web resources.
theme: just-the-docs
url: https://www.navylink.net

color_scheme: nil
search_enabled: false
heading_anchors: false

aux_links:
  GitHub:
    - https://github.com/newnetmp3/navylink.jekyll

exclude:
  - README.md
  - index.md.old
